blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/devioarts/capacitor-tcpclient#documentation
    about: Check the README and docs before opening an issue.
